[package]
name = "doqedev/repldbservice"
version = "0.2.0"
realm = "shared"
description = "Replit's datbase implementation in ROBLOX!"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"

[dependencies]
